//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright (c) 2021 by the OnMetal authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServer) DeepCopyInto(out *APIServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServer.
func (in *APIServer) DeepCopy() *APIServer {
	if in == nil {
		return nil
	}
	out := new(APIServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerAnonymousAuthentication) DeepCopyInto(out *APIServerAnonymousAuthentication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerAnonymousAuthentication.
func (in *APIServerAnonymousAuthentication) DeepCopy() *APIServerAnonymousAuthentication {
	if in == nil {
		return nil
	}
	out := new(APIServerAnonymousAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerAuthentication) DeepCopyInto(out *APIServerAuthentication) {
	*out = *in
	if in.BootstrapToken != nil {
		in, out := &in.BootstrapToken, &out.BootstrapToken
		*out = new(APIServerBootstrapTokenAuthentication)
		**out = **in
	}
	if in.Anonymous != nil {
		in, out := &in.Anonymous, &out.Anonymous
		*out = new(APIServerAnonymousAuthentication)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(APIServerTokenAuthentication)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerAuthentication.
func (in *APIServerAuthentication) DeepCopy() *APIServerAuthentication {
	if in == nil {
		return nil
	}
	out := new(APIServerAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerBootstrapTokenAuthentication) DeepCopyInto(out *APIServerBootstrapTokenAuthentication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerBootstrapTokenAuthentication.
func (in *APIServerBootstrapTokenAuthentication) DeepCopy() *APIServerBootstrapTokenAuthentication {
	if in == nil {
		return nil
	}
	out := new(APIServerBootstrapTokenAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerCondition) DeepCopyInto(out *APIServerCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerCondition.
func (in *APIServerCondition) DeepCopy() *APIServerCondition {
	if in == nil {
		return nil
	}
	out := new(APIServerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerETCD) DeepCopyInto(out *APIServerETCD) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CertificateAuthority != nil {
		in, out := &in.CertificateAuthority, &out.CertificateAuthority
		*out = new(APIServerETCDCertificateAuthority)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(APIServerETCDKey)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerETCD.
func (in *APIServerETCD) DeepCopy() *APIServerETCD {
	if in == nil {
		return nil
	}
	out := new(APIServerETCD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerETCDCertificateAuthority) DeepCopyInto(out *APIServerETCDCertificateAuthority) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerETCDCertificateAuthority.
func (in *APIServerETCDCertificateAuthority) DeepCopy() *APIServerETCDCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(APIServerETCDCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerETCDKey) DeepCopyInto(out *APIServerETCDKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerETCDKey.
func (in *APIServerETCDKey) DeepCopy() *APIServerETCDKey {
	if in == nil {
		return nil
	}
	out := new(APIServerETCDKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerList) DeepCopyInto(out *APIServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerList.
func (in *APIServerList) DeepCopy() *APIServerList {
	if in == nil {
		return nil
	}
	out := new(APIServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerServiceAccount) DeepCopyInto(out *APIServerServiceAccount) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerServiceAccount.
func (in *APIServerServiceAccount) DeepCopy() *APIServerServiceAccount {
	if in == nil {
		return nil
	}
	out := new(APIServerServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerSpec) DeepCopyInto(out *APIServerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ETCD.DeepCopyInto(&out.ETCD)
	in.Authentication.DeepCopyInto(&out.Authentication)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(APIServerTLS)
		**out = **in
	}
	out.ServiceAccount = in.ServiceAccount
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerSpec.
func (in *APIServerSpec) DeepCopy() *APIServerSpec {
	if in == nil {
		return nil
	}
	out := new(APIServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerStatus) DeepCopyInto(out *APIServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerStatus.
func (in *APIServerStatus) DeepCopy() *APIServerStatus {
	if in == nil {
		return nil
	}
	out := new(APIServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerTLS) DeepCopyInto(out *APIServerTLS) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerTLS.
func (in *APIServerTLS) DeepCopy() *APIServerTLS {
	if in == nil {
		return nil
	}
	out := new(APIServerTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIServerTokenAuthentication) DeepCopyInto(out *APIServerTokenAuthentication) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIServerTokenAuthentication.
func (in *APIServerTokenAuthentication) DeepCopy() *APIServerTokenAuthentication {
	if in == nil {
		return nil
	}
	out := new(APIServerTokenAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapSelector) DeepCopyInto(out *ConfigMapSelector) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapSelector.
func (in *ConfigMapSelector) DeepCopy() *ConfigMapSelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManager) DeepCopyInto(out *KubeControllerManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManager.
func (in *KubeControllerManager) DeepCopy() *KubeControllerManager {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeControllerManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerAuthenticationKubeconfig) DeepCopyInto(out *KubeControllerManagerAuthenticationKubeconfig) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerAuthenticationKubeconfig.
func (in *KubeControllerManagerAuthenticationKubeconfig) DeepCopy() *KubeControllerManagerAuthenticationKubeconfig {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerAuthenticationKubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerAuthorizationKubeconfig) DeepCopyInto(out *KubeControllerManagerAuthorizationKubeconfig) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerAuthorizationKubeconfig.
func (in *KubeControllerManagerAuthorizationKubeconfig) DeepCopy() *KubeControllerManagerAuthorizationKubeconfig {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerAuthorizationKubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerCluster) DeepCopyInto(out *KubeControllerManagerCluster) {
	*out = *in
	if in.Signing != nil {
		in, out := &in.Signing, &out.Signing
		*out = new(KubeControllerManagerClusterSigning)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerCluster.
func (in *KubeControllerManagerCluster) DeepCopy() *KubeControllerManagerCluster {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerClusterSigning) DeepCopyInto(out *KubeControllerManagerClusterSigning) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerClusterSigning.
func (in *KubeControllerManagerClusterSigning) DeepCopy() *KubeControllerManagerClusterSigning {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerClusterSigning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerCondition) DeepCopyInto(out *KubeControllerManagerCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerCondition.
func (in *KubeControllerManagerCondition) DeepCopy() *KubeControllerManagerCondition {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerControllers) DeepCopyInto(out *KubeControllerManagerControllers) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerControllers.
func (in *KubeControllerManagerControllers) DeepCopy() *KubeControllerManagerControllers {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerControllers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerKubeconfig) DeepCopyInto(out *KubeControllerManagerKubeconfig) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerKubeconfig.
func (in *KubeControllerManagerKubeconfig) DeepCopy() *KubeControllerManagerKubeconfig {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerKubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerKubernetesAPI) DeepCopyInto(out *KubeControllerManagerKubernetesAPI) {
	*out = *in
	out.Kubeconfig = in.Kubeconfig
	if in.AuthorizationKubeconfig != nil {
		in, out := &in.AuthorizationKubeconfig, &out.AuthorizationKubeconfig
		*out = new(KubeControllerManagerAuthorizationKubeconfig)
		**out = **in
	}
	if in.AuthenticationKubeconfig != nil {
		in, out := &in.AuthenticationKubeconfig, &out.AuthenticationKubeconfig
		*out = new(KubeControllerManagerAuthenticationKubeconfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerKubernetesAPI.
func (in *KubeControllerManagerKubernetesAPI) DeepCopy() *KubeControllerManagerKubernetesAPI {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerKubernetesAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerList) DeepCopyInto(out *KubeControllerManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeControllerManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerList.
func (in *KubeControllerManagerList) DeepCopy() *KubeControllerManagerList {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeControllerManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerServiceAccount) DeepCopyInto(out *KubeControllerManagerServiceAccount) {
	*out = *in
	if in.RootCertificateAuthority != nil {
		in, out := &in.RootCertificateAuthority, &out.RootCertificateAuthority
		*out = new(KubeControllerManagerServiceAccountRootCertificateAuthority)
		**out = **in
	}
	out.PrivateKey = in.PrivateKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerServiceAccount.
func (in *KubeControllerManagerServiceAccount) DeepCopy() *KubeControllerManagerServiceAccount {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerServiceAccountPrivateKey) DeepCopyInto(out *KubeControllerManagerServiceAccountPrivateKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerServiceAccountPrivateKey.
func (in *KubeControllerManagerServiceAccountPrivateKey) DeepCopy() *KubeControllerManagerServiceAccountPrivateKey {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerServiceAccountPrivateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerServiceAccountRootCertificateAuthority) DeepCopyInto(out *KubeControllerManagerServiceAccountRootCertificateAuthority) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerServiceAccountRootCertificateAuthority.
func (in *KubeControllerManagerServiceAccountRootCertificateAuthority) DeepCopy() *KubeControllerManagerServiceAccountRootCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerServiceAccountRootCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerSpec) DeepCopyInto(out *KubeControllerManagerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Cluster.DeepCopyInto(&out.Cluster)
	in.Controllers.DeepCopyInto(&out.Controllers)
	in.KubernetesAPI.DeepCopyInto(&out.KubernetesAPI)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerSpec.
func (in *KubeControllerManagerSpec) DeepCopy() *KubeControllerManagerSpec {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerStatus) DeepCopyInto(out *KubeControllerManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerStatus.
func (in *KubeControllerManagerStatus) DeepCopy() *KubeControllerManagerStatus {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubeconfig) DeepCopyInto(out *Kubeconfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubeconfig.
func (in *Kubeconfig) DeepCopy() *Kubeconfig {
	if in == nil {
		return nil
	}
	out := new(Kubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kubeconfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfo) DeepCopyInto(out *KubeconfigAuthInfo) {
	*out = *in
	if in.ClientCertificate != nil {
		in, out := &in.ClientCertificate, &out.ClientCertificate
		*out = new(KubeconfigAuthInfoClientCertificate)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientKey != nil {
		in, out := &in.ClientKey, &out.ClientKey
		*out = new(KubeconfigAuthInfoClientKey)
		(*in).DeepCopyInto(*out)
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(KubeconfigAuthInfoToken)
		(*in).DeepCopyInto(*out)
	}
	if in.ImpersonateGroups != nil {
		in, out := &in.ImpersonateGroups, &out.ImpersonateGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(KubeconfigAuthInfoPassword)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfo.
func (in *KubeconfigAuthInfo) DeepCopy() *KubeconfigAuthInfo {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfoClientCertificate) DeepCopyInto(out *KubeconfigAuthInfoClientCertificate) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfoClientCertificate.
func (in *KubeconfigAuthInfoClientCertificate) DeepCopy() *KubeconfigAuthInfoClientCertificate {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfoClientCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfoClientKey) DeepCopyInto(out *KubeconfigAuthInfoClientKey) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfoClientKey.
func (in *KubeconfigAuthInfoClientKey) DeepCopy() *KubeconfigAuthInfoClientKey {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfoClientKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfoPassword) DeepCopyInto(out *KubeconfigAuthInfoPassword) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfoPassword.
func (in *KubeconfigAuthInfoPassword) DeepCopy() *KubeconfigAuthInfoPassword {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfoPassword)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfoToken) DeepCopyInto(out *KubeconfigAuthInfoToken) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfoToken.
func (in *KubeconfigAuthInfoToken) DeepCopy() *KubeconfigAuthInfoToken {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfoToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigCluster) DeepCopyInto(out *KubeconfigCluster) {
	*out = *in
	if in.CertificateAuthority != nil {
		in, out := &in.CertificateAuthority, &out.CertificateAuthority
		*out = new(KubeconfigClusterCertificateAuthority)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigCluster.
func (in *KubeconfigCluster) DeepCopy() *KubeconfigCluster {
	if in == nil {
		return nil
	}
	out := new(KubeconfigCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigClusterCertificateAuthority) DeepCopyInto(out *KubeconfigClusterCertificateAuthority) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigClusterCertificateAuthority.
func (in *KubeconfigClusterCertificateAuthority) DeepCopy() *KubeconfigClusterCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(KubeconfigClusterCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigContext) DeepCopyInto(out *KubeconfigContext) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigContext.
func (in *KubeconfigContext) DeepCopy() *KubeconfigContext {
	if in == nil {
		return nil
	}
	out := new(KubeconfigContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigList) DeepCopyInto(out *KubeconfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kubeconfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigList.
func (in *KubeconfigList) DeepCopy() *KubeconfigList {
	if in == nil {
		return nil
	}
	out := new(KubeconfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeconfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigNamedAuthInfo) DeepCopyInto(out *KubeconfigNamedAuthInfo) {
	*out = *in
	in.AuthInfo.DeepCopyInto(&out.AuthInfo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigNamedAuthInfo.
func (in *KubeconfigNamedAuthInfo) DeepCopy() *KubeconfigNamedAuthInfo {
	if in == nil {
		return nil
	}
	out := new(KubeconfigNamedAuthInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigNamedCluster) DeepCopyInto(out *KubeconfigNamedCluster) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigNamedCluster.
func (in *KubeconfigNamedCluster) DeepCopy() *KubeconfigNamedCluster {
	if in == nil {
		return nil
	}
	out := new(KubeconfigNamedCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigNamedContext) DeepCopyInto(out *KubeconfigNamedContext) {
	*out = *in
	out.Context = in.Context
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigNamedContext.
func (in *KubeconfigNamedContext) DeepCopy() *KubeconfigNamedContext {
	if in == nil {
		return nil
	}
	out := new(KubeconfigNamedContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigSpec) DeepCopyInto(out *KubeconfigSpec) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]KubeconfigNamedCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthInfos != nil {
		in, out := &in.AuthInfos, &out.AuthInfos
		*out = make([]KubeconfigNamedAuthInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Contexts != nil {
		in, out := &in.Contexts, &out.Contexts
		*out = make([]KubeconfigNamedContext, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigSpec.
func (in *KubeconfigSpec) DeepCopy() *KubeconfigSpec {
	if in == nil {
		return nil
	}
	out := new(KubeconfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigStatus) DeepCopyInto(out *KubeconfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigStatus.
func (in *KubeconfigStatus) DeepCopy() *KubeconfigStatus {
	if in == nil {
		return nil
	}
	out := new(KubeconfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSelector) DeepCopyInto(out *SecretSelector) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSelector.
func (in *SecretSelector) DeepCopy() *SecretSelector {
	if in == nil {
		return nil
	}
	out := new(SecretSelector)
	in.DeepCopyInto(out)
	return out
}
