//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright (c) 2021 by the OnMetal authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapSelector) DeepCopyInto(out *ConfigMapSelector) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapSelector.
func (in *ConfigMapSelector) DeepCopy() *ConfigMapSelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServer) DeepCopyInto(out *KubeAPIServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServer.
func (in *KubeAPIServer) DeepCopy() *KubeAPIServer {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeAPIServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerAnonymousAuthentication) DeepCopyInto(out *KubeAPIServerAnonymousAuthentication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerAnonymousAuthentication.
func (in *KubeAPIServerAnonymousAuthentication) DeepCopy() *KubeAPIServerAnonymousAuthentication {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerAnonymousAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerAuthentication) DeepCopyInto(out *KubeAPIServerAuthentication) {
	*out = *in
	if in.BootstrapToken != nil {
		in, out := &in.BootstrapToken, &out.BootstrapToken
		*out = new(KubeAPIServerBootstrapTokenAuthentication)
		**out = **in
	}
	if in.Anonymous != nil {
		in, out := &in.Anonymous, &out.Anonymous
		*out = new(KubeAPIServerAnonymousAuthentication)
		**out = **in
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(KubeAPIServerTokenAuthentication)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerAuthentication.
func (in *KubeAPIServerAuthentication) DeepCopy() *KubeAPIServerAuthentication {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerBootstrapTokenAuthentication) DeepCopyInto(out *KubeAPIServerBootstrapTokenAuthentication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerBootstrapTokenAuthentication.
func (in *KubeAPIServerBootstrapTokenAuthentication) DeepCopy() *KubeAPIServerBootstrapTokenAuthentication {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerBootstrapTokenAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerCondition) DeepCopyInto(out *KubeAPIServerCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerCondition.
func (in *KubeAPIServerCondition) DeepCopy() *KubeAPIServerCondition {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerETCD) DeepCopyInto(out *KubeAPIServerETCD) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CertificateAuthority != nil {
		in, out := &in.CertificateAuthority, &out.CertificateAuthority
		*out = new(KubeAPIServerETCDCertificateAuthority)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(KubeAPIServerETCDKey)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerETCD.
func (in *KubeAPIServerETCD) DeepCopy() *KubeAPIServerETCD {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerETCD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerETCDCertificateAuthority) DeepCopyInto(out *KubeAPIServerETCDCertificateAuthority) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerETCDCertificateAuthority.
func (in *KubeAPIServerETCDCertificateAuthority) DeepCopy() *KubeAPIServerETCDCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerETCDCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerETCDKey) DeepCopyInto(out *KubeAPIServerETCDKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerETCDKey.
func (in *KubeAPIServerETCDKey) DeepCopy() *KubeAPIServerETCDKey {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerETCDKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerList) DeepCopyInto(out *KubeAPIServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeAPIServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerList.
func (in *KubeAPIServerList) DeepCopy() *KubeAPIServerList {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeAPIServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerServiceAccount) DeepCopyInto(out *KubeAPIServerServiceAccount) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerServiceAccount.
func (in *KubeAPIServerServiceAccount) DeepCopy() *KubeAPIServerServiceAccount {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerSpec) DeepCopyInto(out *KubeAPIServerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ETCD.DeepCopyInto(&out.ETCD)
	in.Authentication.DeepCopyInto(&out.Authentication)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(KubeAPIServerTLS)
		**out = **in
	}
	out.ServiceAccount = in.ServiceAccount
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerSpec.
func (in *KubeAPIServerSpec) DeepCopy() *KubeAPIServerSpec {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerStatus) DeepCopyInto(out *KubeAPIServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerStatus.
func (in *KubeAPIServerStatus) DeepCopy() *KubeAPIServerStatus {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerTLS) DeepCopyInto(out *KubeAPIServerTLS) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerTLS.
func (in *KubeAPIServerTLS) DeepCopy() *KubeAPIServerTLS {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeAPIServerTokenAuthentication) DeepCopyInto(out *KubeAPIServerTokenAuthentication) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeAPIServerTokenAuthentication.
func (in *KubeAPIServerTokenAuthentication) DeepCopy() *KubeAPIServerTokenAuthentication {
	if in == nil {
		return nil
	}
	out := new(KubeAPIServerTokenAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManager) DeepCopyInto(out *KubeControllerManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManager.
func (in *KubeControllerManager) DeepCopy() *KubeControllerManager {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeControllerManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerAuthenticationKubeconfig) DeepCopyInto(out *KubeControllerManagerAuthenticationKubeconfig) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerAuthenticationKubeconfig.
func (in *KubeControllerManagerAuthenticationKubeconfig) DeepCopy() *KubeControllerManagerAuthenticationKubeconfig {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerAuthenticationKubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerAuthorizationKubeconfig) DeepCopyInto(out *KubeControllerManagerAuthorizationKubeconfig) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerAuthorizationKubeconfig.
func (in *KubeControllerManagerAuthorizationKubeconfig) DeepCopy() *KubeControllerManagerAuthorizationKubeconfig {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerAuthorizationKubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerCluster) DeepCopyInto(out *KubeControllerManagerCluster) {
	*out = *in
	if in.Signing != nil {
		in, out := &in.Signing, &out.Signing
		*out = new(KubeControllerManagerClusterSigning)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerCluster.
func (in *KubeControllerManagerCluster) DeepCopy() *KubeControllerManagerCluster {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerClusterSigning) DeepCopyInto(out *KubeControllerManagerClusterSigning) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerClusterSigning.
func (in *KubeControllerManagerClusterSigning) DeepCopy() *KubeControllerManagerClusterSigning {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerClusterSigning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerCondition) DeepCopyInto(out *KubeControllerManagerCondition) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerCondition.
func (in *KubeControllerManagerCondition) DeepCopy() *KubeControllerManagerCondition {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerControllers) DeepCopyInto(out *KubeControllerManagerControllers) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerControllers.
func (in *KubeControllerManagerControllers) DeepCopy() *KubeControllerManagerControllers {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerControllers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerKubeconfig) DeepCopyInto(out *KubeControllerManagerKubeconfig) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerKubeconfig.
func (in *KubeControllerManagerKubeconfig) DeepCopy() *KubeControllerManagerKubeconfig {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerKubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerKubernetesAPI) DeepCopyInto(out *KubeControllerManagerKubernetesAPI) {
	*out = *in
	out.Kubeconfig = in.Kubeconfig
	if in.AuthorizationKubeconfig != nil {
		in, out := &in.AuthorizationKubeconfig, &out.AuthorizationKubeconfig
		*out = new(KubeControllerManagerAuthorizationKubeconfig)
		**out = **in
	}
	if in.AuthenticationKubeconfig != nil {
		in, out := &in.AuthenticationKubeconfig, &out.AuthenticationKubeconfig
		*out = new(KubeControllerManagerAuthenticationKubeconfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerKubernetesAPI.
func (in *KubeControllerManagerKubernetesAPI) DeepCopy() *KubeControllerManagerKubernetesAPI {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerKubernetesAPI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerList) DeepCopyInto(out *KubeControllerManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KubeControllerManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerList.
func (in *KubeControllerManagerList) DeepCopy() *KubeControllerManagerList {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeControllerManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerServiceAccount) DeepCopyInto(out *KubeControllerManagerServiceAccount) {
	*out = *in
	if in.RootCertificateAuthority != nil {
		in, out := &in.RootCertificateAuthority, &out.RootCertificateAuthority
		*out = new(KubeControllerManagerServiceAccountRootCertificateAuthority)
		**out = **in
	}
	out.PrivateKey = in.PrivateKey
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerServiceAccount.
func (in *KubeControllerManagerServiceAccount) DeepCopy() *KubeControllerManagerServiceAccount {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerServiceAccountPrivateKey) DeepCopyInto(out *KubeControllerManagerServiceAccountPrivateKey) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerServiceAccountPrivateKey.
func (in *KubeControllerManagerServiceAccountPrivateKey) DeepCopy() *KubeControllerManagerServiceAccountPrivateKey {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerServiceAccountPrivateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerServiceAccountRootCertificateAuthority) DeepCopyInto(out *KubeControllerManagerServiceAccountRootCertificateAuthority) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerServiceAccountRootCertificateAuthority.
func (in *KubeControllerManagerServiceAccountRootCertificateAuthority) DeepCopy() *KubeControllerManagerServiceAccountRootCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerServiceAccountRootCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerSpec) DeepCopyInto(out *KubeControllerManagerSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Cluster.DeepCopyInto(&out.Cluster)
	in.Controllers.DeepCopyInto(&out.Controllers)
	in.KubernetesAPI.DeepCopyInto(&out.KubernetesAPI)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerSpec.
func (in *KubeControllerManagerSpec) DeepCopy() *KubeControllerManagerSpec {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeControllerManagerStatus) DeepCopyInto(out *KubeControllerManagerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeControllerManagerStatus.
func (in *KubeControllerManagerStatus) DeepCopy() *KubeControllerManagerStatus {
	if in == nil {
		return nil
	}
	out := new(KubeControllerManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubeconfig) DeepCopyInto(out *Kubeconfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubeconfig.
func (in *Kubeconfig) DeepCopy() *Kubeconfig {
	if in == nil {
		return nil
	}
	out := new(Kubeconfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kubeconfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfo) DeepCopyInto(out *KubeconfigAuthInfo) {
	*out = *in
	if in.ClientCertificate != nil {
		in, out := &in.ClientCertificate, &out.ClientCertificate
		*out = new(KubeconfigAuthInfoClientCertificate)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientKey != nil {
		in, out := &in.ClientKey, &out.ClientKey
		*out = new(KubeconfigAuthInfoClientKey)
		(*in).DeepCopyInto(*out)
	}
	if in.Token != nil {
		in, out := &in.Token, &out.Token
		*out = new(KubeconfigAuthInfoToken)
		(*in).DeepCopyInto(*out)
	}
	if in.ImpersonateGroups != nil {
		in, out := &in.ImpersonateGroups, &out.ImpersonateGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(KubeconfigAuthInfoPassword)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfo.
func (in *KubeconfigAuthInfo) DeepCopy() *KubeconfigAuthInfo {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfoClientCertificate) DeepCopyInto(out *KubeconfigAuthInfoClientCertificate) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfoClientCertificate.
func (in *KubeconfigAuthInfoClientCertificate) DeepCopy() *KubeconfigAuthInfoClientCertificate {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfoClientCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfoClientKey) DeepCopyInto(out *KubeconfigAuthInfoClientKey) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfoClientKey.
func (in *KubeconfigAuthInfoClientKey) DeepCopy() *KubeconfigAuthInfoClientKey {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfoClientKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfoPassword) DeepCopyInto(out *KubeconfigAuthInfoPassword) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfoPassword.
func (in *KubeconfigAuthInfoPassword) DeepCopy() *KubeconfigAuthInfoPassword {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfoPassword)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigAuthInfoToken) DeepCopyInto(out *KubeconfigAuthInfoToken) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigAuthInfoToken.
func (in *KubeconfigAuthInfoToken) DeepCopy() *KubeconfigAuthInfoToken {
	if in == nil {
		return nil
	}
	out := new(KubeconfigAuthInfoToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigCluster) DeepCopyInto(out *KubeconfigCluster) {
	*out = *in
	if in.CertificateAuthority != nil {
		in, out := &in.CertificateAuthority, &out.CertificateAuthority
		*out = new(KubeconfigClusterCertificateAuthority)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigCluster.
func (in *KubeconfigCluster) DeepCopy() *KubeconfigCluster {
	if in == nil {
		return nil
	}
	out := new(KubeconfigCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigClusterCertificateAuthority) DeepCopyInto(out *KubeconfigClusterCertificateAuthority) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(SecretSelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigClusterCertificateAuthority.
func (in *KubeconfigClusterCertificateAuthority) DeepCopy() *KubeconfigClusterCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(KubeconfigClusterCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigContext) DeepCopyInto(out *KubeconfigContext) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigContext.
func (in *KubeconfigContext) DeepCopy() *KubeconfigContext {
	if in == nil {
		return nil
	}
	out := new(KubeconfigContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigList) DeepCopyInto(out *KubeconfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kubeconfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigList.
func (in *KubeconfigList) DeepCopy() *KubeconfigList {
	if in == nil {
		return nil
	}
	out := new(KubeconfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubeconfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigNamedAuthInfo) DeepCopyInto(out *KubeconfigNamedAuthInfo) {
	*out = *in
	in.AuthInfo.DeepCopyInto(&out.AuthInfo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigNamedAuthInfo.
func (in *KubeconfigNamedAuthInfo) DeepCopy() *KubeconfigNamedAuthInfo {
	if in == nil {
		return nil
	}
	out := new(KubeconfigNamedAuthInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigNamedCluster) DeepCopyInto(out *KubeconfigNamedCluster) {
	*out = *in
	in.Cluster.DeepCopyInto(&out.Cluster)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigNamedCluster.
func (in *KubeconfigNamedCluster) DeepCopy() *KubeconfigNamedCluster {
	if in == nil {
		return nil
	}
	out := new(KubeconfigNamedCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigNamedContext) DeepCopyInto(out *KubeconfigNamedContext) {
	*out = *in
	out.Context = in.Context
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigNamedContext.
func (in *KubeconfigNamedContext) DeepCopy() *KubeconfigNamedContext {
	if in == nil {
		return nil
	}
	out := new(KubeconfigNamedContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigSpec) DeepCopyInto(out *KubeconfigSpec) {
	*out = *in
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]KubeconfigNamedCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthInfos != nil {
		in, out := &in.AuthInfos, &out.AuthInfos
		*out = make([]KubeconfigNamedAuthInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Contexts != nil {
		in, out := &in.Contexts, &out.Contexts
		*out = make([]KubeconfigNamedContext, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigSpec.
func (in *KubeconfigSpec) DeepCopy() *KubeconfigSpec {
	if in == nil {
		return nil
	}
	out := new(KubeconfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigStatus) DeepCopyInto(out *KubeconfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigStatus.
func (in *KubeconfigStatus) DeepCopy() *KubeconfigStatus {
	if in == nil {
		return nil
	}
	out := new(KubeconfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretSelector) DeepCopyInto(out *SecretSelector) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretSelector.
func (in *SecretSelector) DeepCopy() *SecretSelector {
	if in == nil {
		return nil
	}
	out := new(SecretSelector)
	in.DeepCopyInto(out)
	return out
}
