# permissions for end users to edit apiservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apiserver-editor-role
rules:
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - apiservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - apiservers/status
  verbs:
  - get
