# permissions for end users to view kubeapiservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeapiserver-viewer-role
rules:
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - kubeapiservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - kubeapiservers/status
  verbs:
  - get
