# permissions for end users to view kubecontrollermanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubecontrollermanager-viewer-role
rules:
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - kubecontrollermanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - kubecontrollermanagers/status
  verbs:
  - get
