# permissions for end users to edit kubeapiservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeapiserver-editor-role
rules:
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - kubeapiservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - kubeapiservers/status
  verbs:
  - get
