# permissions for end users to edit kubeschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubescheduler-editor-role
rules:
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - kubeschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matryoshka.onmetal.de
  resources:
  - kubeschedulers/status
  verbs:
  - get
