apiVersion: v1
kind: Secret
metadata:
  name: my-password
data:
  password: bXlzdXBlcnNhZmVwYXNzd29yZA==
---
apiVersion: matryoshka.onmetal.de/v1alpha1
kind: Kubeconfig
metadata:
  name: kubeconfig-sample
spec:
  # Add fields here
  secretName: my-kubeconfig
  currentContext: default
  clusters:
  - name: default
    cluster:
      server: http://localhost:8080
      insecureSkipTLSVerify: true
  users:
  - name: default
    user:
      username: default
      passwordSecret:
        name: my-password
  contexts:
  - name: default
    context:
      cluster: default
      user: default
