apiVersion: v1
kind: Service
metadata:
  name: apiserver-sample
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    matryoshka.onmetal.de/app: kubeapiserver-apiserver-sample
---
apiVersion: v1
kind: Secret
metadata:
  name: ks-token
stringData:
  token: some-token
---
apiVersion: matryoshka.onmetal.de/v1alpha1
kind: Kubeconfig
metadata:
  name: ks-kubeconfig
spec:
  clusters:
    - cluster:
        server: https://apiserver-sample
        insecureSkipTLSVerify: true
      name: current
  contexts:
    - context:
        cluster: current
        user: admin
      name: current
  currentContext: current
  secretName: ks-kubeconfig
  users:
    - name: admin
      user:
        tokenSecret:
          name: ks-token
---
apiVersion: matryoshka.onmetal.de/v1alpha1
kind: KubeScheduler
metadata:
  name: kubescheduler-sample
spec:
  replicas: 1
  version: 1.22.1
  componentConfig:
    kubeconfigSecret:
      name: ks-kubeconfig
  authentication:
    skipLookup: true
    kubeconfigSecret:
      name: ks-kubeconfig
  authorization:
    kubeconfigSecret:
      name: ks-kubeconfig
  overlay:
    metadata:
      labels:
        foo: bar
  featureGates:
    NodeSwap: false # as of k8s 1.22, beta feature, default true
